alias zls='zoxide query -l'
alias zr='zoxide remove'
alias za='zoxide add'


if [ -z "$TMUX" ]; then
  tmux
fi


g() {
    g() {
  if [[ -z "$1" ]]; then
    echo "Error: No source file provided."
    return 1
  fi

  if ! gcc "$1"; then
    echo "Compilation failed."
    return 1
  fi

  echo "Press any key to execute the file..."
  read -n 1 -s

  if [[ -x "./a.out" ]]; then
    ./a.out
  else
    echo "Executable not found or not executable."
    return 1
  fi
}

}

p() {
    if [[ -z "$1" ]]; then
        echo "Error: No source file provided."
        return 1
    fi

    if ! python3 "$1"; then
        echo "CF!!!"
        return 1
    fi

}

