#
# ~/.bashrc
#


alias l='ls -CF'
alias la='ls -Fla'

alias zls='zoxide query -l'
alias zr='zoxide remove'
alias za='zoxide add'

export PATH="$HOME/.local/bin:$PATH"
eval "$(zoxide init bash)"




if [ -z "$TMUX" ]; then
  tmux
fi

gacp() {
    if [[ -z "$1" ]]; then
        echo "No Message Provided"
        echo "You Must Provide A Message For The Commit"
        return 1
    fi
    git add .
    git commit -m "$1"
    git push origin main
}


g() {
    g() {
  if [[ -z "$1" ]]; then
    echo "Error: No source file provided."
    return 1
  fi

  if ! gcc "$1"; then
    echo "Compilation failed."
    return 1
  fi

  echo "Press any key to execute the file..."
  read -n 1 -s

  if [[ -x "./a.out" ]]; then
    ./a.out
  else
    echo "Executable not found or not executable."
    return 1
  fi
}

}

p() {
    if [[ -z "$1" ]]; then
        echo "Error: No source file provided as the first argument."
        return 1
    fi

    if [[ ! -f "$1" ]]; then
        echo "Error: The first argument is not a file"
        return 1
    fi

    if [[ "$1" != *.py  ]]; then
        echo "Error: The first argument is not a Python (.py) file"
        return 1
    fi

    script="$1"
    shift # This removes $1 from the equation when doing $@

    if ! python3 "$script" "$@"; then
        echo "CF!!!"
        return 1
    fi

}
