
"""""""""""
" vim-plug
"""""""""""
" To vim-plug:
" curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
" https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
"
" To install plugins:
" :PlugInstall
"""""""""""
if &compatible
  set nocompatible               " Be iMproved
endif

" Initialize vim-plug
call plug#begin('~/.vim/plugged')

" Plugins
Plug 'easymotion/vim-easymotion'

" End vim-plug setup
call plug#end()


" Built-in Plugins
syntax enable
set smartindent
set autoindent
set tabstop=4
set shiftwidth=4
set expandtab
set scrolloff=7
set number relativenumber
set virtualedit=all

" Key-binds
let mapleader = " "
vnoremap J :m '>+1<CR>gv=gv
vnoremap K :m '<-2<CR>gv=gv
inoremap <C-H> <C-W>
nmap <leader>f <Plug>(easymotion-bd-w)
nnoremap diw diwx
nnoremap ;n :bn<CR>
nnoremap ;ln :call ToggleLineNumbers()<CR>
nnoremap Q :q!<CR>
nnoremap <leader>e :e 
nnoremap <leader>P :call ToggleP()<CR>
nnoremap <leader>D :Ex<CR>
nnoremap <leader>d ggVGdka<CR>
" nnoremap <leader>P :!clear; echo "-------"; sleep .25; python3 main.py<CR>
nnoremap <leader>cat :call COPY()<CR>
xnoremap <leader>p "_dP_
nnoremap ;f vf)y`lp==

" Functions
function! ToggleLineNumbers()
  if &number && &relativenumber
    set nonumber norelativenumber
  else
    set number relativenumber
  endif
endfunction

function! ToggleP() 
    w
    !clear; echo "-------"; sleep .25; python3 main.py
endfunction

function! COPY() 
    w
    let filename = expand('%:p')
    execute '!clear; cat ' . shellescape(filename)
endfunction

" Snippets
" The line below is an example of how to insert code snippets with keybindings
" noremap ,cb :-1read ~/snippets/codeBubble.md<CR>ji
noremap ,pp :-1read ~/snippets/py_print.py<CR>==ci"
noremap ,pf :-1read ~/snippets/py_func.py<CR>==fFciw
noremap ,plf :-1read ~/snippets/py_for.py<CR>==fvciw
