
"""""""""""
" vim-plug
"""""""""""
" To vim-plug:
" curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
" https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
"
" To install plugins:
" :PlugInstall
"""""""""""
if &compatible
  set nocompatible               " Be iMproved
endif

" Initialize vim-plug
call plug#begin('~/.vim/plugged')

" Plugins
Plug 'easymotion/vim-easymotion'

" End vim-plug setup
call plug#end()


" Built-in Plugins
syntax enable
set smartindent
set autoindent
set tabstop=4
set shiftwidth=4
set expandtab
set scrolloff=7
set number relativenumber
set virtualedit=all

" Key-binds
let mapleader = " "
vnoremap J :m '>+1<CR>gv=gv
vnoremap K :m '<-2<CR>gv=gv
inoremap <C-H> <C-W>
nmap <leader>f <Plug>(easymotion-bd-w)
nnoremap diw diwx
nnoremap ;n :bn<CR>
nnoremap <leader>d :Ex<CR>
nnoremap ;ln :call ToggleLineNumbers()<CR>
nnoremap Q :q!<CR>
nnoremap <leader>e :e
nnoremap <leader>P :!clear; echo "-------"; sleep .25; python3 main.py<CR>
xnoremap <leader>p "_dP_

" Functions
function! ToggleLineNumbers()
  if &number && &relativenumber
    set nonumber norelativenumber
  else
    set number relativenumber
  endif
endfunction


" Snippets
" The line below is an example of how to insert code snippets with keybindings
" noremap ,cb :-1read ~/snippets/codeBubble.md<CR>ji
