[pyprland]

include = ["~/.config/hypr/pyprland.d"]

plugins = [
 "expose",
 "fetch_client_menu",
 "lost_windows",
 "magnify",
 "scratchpads",
 "shift_monitors",
 "toggle_special",
 "workspaces_follow_focus",
]

# using variables for demonstration purposes (not needed)

[pyprland.variables]
term_classed = "kitty --class"


